// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("Client")]
public partial class Client
{
    [Key]
    public int ClientID { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string LastName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Role { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [StringLength(64)]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Address1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Address2 { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string City { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [Column("Status")]
    public string Status { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Province { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Company { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    [Column("PwdToken")]
    public string PwdToken { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();
}