// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("DrawingRequest")]
public partial class DrawingRequest
{
    [Key]
    public int DrawingRequestID { get; set; }

    public int? PackageID { get; set; }

    public bool? IssuedForConstruction { get; set; }

    public bool? WeldMapComplete { get; set; }

    public bool? ThicknessRangeQualifiedAcceptable { get; set; }

    public bool? CorrectWPS { get; set; }

    public int EmployeeID { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("DrawingRequests")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("PackageID")]
    [InverseProperty("DrawingRequests")]
    public virtual Package Package { get; set; }
}