// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public int EmployeeID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [StringLength(64)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Address1 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Address2 { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Role { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Province { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    [Column("PwdToken")]
    public string PwdToken { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [Column("Status")]
    public string Status { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<DrawingRequest> DrawingRequests { get; set; } = new List<DrawingRequest>();


}