// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("Event")]
public partial class EventItem
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    [StringLength(10)] [Unicode(false)] public string Type { get; set; }
    public int ClientID { get; set; }
    [Column(TypeName = "date")] public DateTime Regist { get; set; }
    public int TargetID { get; set; }
    [StringLength(10)][Unicode(false)] public string Role { get; set; }
    [StringLength(20)][Unicode(false)] public string Username { get; set; }
    [StringLength(20)][Unicode(false)] public string PackageNo { get; set; }
    [StringLength(20)][Unicode(false)] public string WPSNo { get; set; }
}