// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("Filler")]
public partial class Filler
{
    [Key]
    public int FillerID { get; set; }

    public int? WPSFormID { get; set; }

    public bool? SFA { get; set; }

    public bool? FNo { get; set; }

    public bool? ANo { get; set; }

    public bool? SizeMatchesPQR { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TypeOfProductForm { get; set; }

    public bool? ProductFormMatchesPQR { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string AdditionalCommentFormMatchPQR { get; set; }

    public bool? SupplementalUsed { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string AdditionalCommentSupplementUsed { get; set; }

    public bool? DepositThickness { get; set; }

    public bool? ConsumableInsert { get; set; }

    [ForeignKey("WPSFormID")]
    [InverseProperty("Fillers")]
    public virtual WP WPSForm { get; set; }
}