// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("FillerMetal")]
public partial class FillerMetal
{
    [Key]
    public int ElectrodeFluxClassificationID { get; set; }

    public bool? ElectrodeFluxClassificationCorrect { get; set; }

    public int? WPSFormID { get; set; }

    public bool? FluxTradeNameStatedCorrect { get; set; }

    public bool? FluxTradeNameNotStated { get; set; }

    public bool? FluxTradeStatedAsManufacture { get; set; }

    [ForeignKey("WPSFormID")]
    [InverseProperty("FillerMetals")]
    public virtual WP WPSForm { get; set; }
}