// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("Position")]
public partial class Position
{
    public int? WPSFormID { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string PositionID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PositionType { get; set; }

    public bool? OverheadVertical { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string TypeOfProgression { get; set; }

    public bool? ProgressionRestriction { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AdditionalComment { get; set; }

    [ForeignKey("WPSFormID")]
    [InverseProperty("Positions")]
    public virtual WP WPSForm { get; set; }
}