// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("PreheatAndPostWeld")]
public partial class PreheatAndPostWeld
{
    [Key]
    public int HeatID { get; set; }

    public int? WPSFormID { get; set; }

    public bool? PreheatMinCorrect { get; set; }

    public bool? InterpassMaxCorrect { get; set; }

    public bool? PreheatMaintenanceRequired { get; set; }

    public bool? PWHTTempRangeCorrect { get; set; }

    public bool? PWHTSoakTimeCorrect { get; set; }

    public bool? SolutionAnnealRequired { get; set; }

    public bool? PostWeldRequired { get; set; }

    [ForeignKey("WPSFormID")]
    [InverseProperty("PreheatAndPostWelds")]
    public virtual WP WPSForm { get; set; }
}