// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("WeldingProcess")]
public partial class WeldingProcess
{
    [Key]
    public int WeldingProcessID { get; set; }

    public int? WPSFormID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ProcessType { get; set; }

    public bool Backing { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TypeOfBacking { get; set; }

    public bool MaxThicknessRange { get; set; }

    public bool MaxPassThicknessRange { get; set; }

    [ForeignKey("WPSFormID")]
    [InverseProperty("WeldingProcesses")]
    public virtual WP WPSForm { get; set; }
}