// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkFlowSystem.Entities;

[Table("WPS1")]
public partial class WP
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int WPSFormID { get; set; }

    public int? PackageID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string WPSNo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PQRNumber { get; set; }

    public int? EmployeeID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CompanyName { get; set; }

    [Column(TypeName = "DateTime")]
    public DateTime? Date { get; set; }

    [StringLength(2048)]
    [Unicode(false)]
    public string Detail { get; set; }
}